3d lesson
alesia-pashuk/js-mentoring-program pull request #3
Opened 2022-02-23 12:25 UTC by alesia-pashuk

2022-02-23 15:07 UTC, eugs requested changes

2022-02-23 15:07 UTC, eugs commented on tasks/cycles/cycles.js
> +i = 1;
лучше не переиспользовать старые счётчики, тк иногда это может дать непредвиденные результаты

в целом тут вообще получается, что **i** в 18 строке - НЕ то же `let i = 1` из 13-й
у `let` блочная область видимости, она видна только внутри блока `for`

просто в жс можно объявить переменную без let/const/var, что и происходить в 18 строке

это легко проверить, если попробовать вывести `i` между блоками, добавив `console.log(i)`

<img width="330" alt="image" src="https://user-images.githubusercontent.com/29432117/155345286-4909f51c-b86c-455c-ab2a-d852d3aebb3f.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/29432117/155345380-05d5c318-0b92-4230-ad2d-918b4261722c.png">

лучше для каждого цикла сделать новые счётчики

2022-02-23 15:07 UTC, eugs commented on tasks/cycles/cycles.js
> +i = 1;
то же самое с `i`

2022-02-23 15:07 UTC, eugs commented on tasks/cycles/cycles.js
> +for (let key of substr) {
just FYI

называя переменную key мы как бы имеем в виду, что перебираем ключи объекта/массива, когда на самом деле перебираем **не ключи**, а **значения**

просто для логики можно переименовать

(по желанию)

2022-02-23 15:07 UTC, eugs commented on tasks/cycles/cycles.js
> +  sum += personIncomes[key];
нужна ли нам вообще переменная `sum`?

(по желанию)

2022-02-23 15:10 UTC, eugs commented on tasks/condition/condition.js
> +y < 10 ? (z2 = x + y) : (z2 = x * y);
тернарка возвращает наружу результат выбранного выражения:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/29432117/155347246-ab8e7b5c-800c-4d0e-b1b9-7f3e252a5572.png">

2022-02-23 15:11 UTC, eugs commented on tasks/condition/condition.js
> +y < 10 ? (z2 = x + y) : (z2 = x * y);
ну или так

<img width="549" alt="image" src="https://user-images.githubusercontent.com/29432117/155347399-420e878a-e71b-4914-9dab-2e94df1cf0e7.png">

2022-03-22 13:04 UTC, alesia-pashuk commented on tasks/condition/condition.js
> +y < 10 ? (z2 = x + y) : (z2 = x * y);
Разобралась, поправилась, перепроверила. Спасибо!

<img width="412" alt="1" src="https://user-images.githubusercontent.com/91085705/159488275-5026a2a3-1e2f-4ede-b333-5ce02b611ff7.PNG">
.

2022-03-22 13:05 UTC, alesia-pashuk commented on tasks/condition/condition.js
> +else if (redemption >= 2700 && redemption <= 6500) discount = 45;
Тут я невнимательно скопировала условие, моя ошибка. Поправила.

2022-03-22 13:47 UTC, alesia-pashuk commented on tasks/cycles/cycles.js
> +i = 1;
Про блочную область видимости let поняла. Это было в теории, но я не применила ее вовремя и где надо. Поправила переменную:

<img width="197" alt="2" src="https://user-images.githubusercontent.com/91085705/159495468-51b0a88e-cbc9-44a1-bdf8-b0281a72560e.png">

Про новые счетчики: я вдруг засомневалась, что правильно понимаю, что это такое. Счетчик - это моя объявленная переменная для каждого из циклов задания на факториал? Я везде использую одноименную i, но правильнее было бы свою переменную для каждого нового цикла, так? 
Например:
for - i
while - a
do while - b

Иил не так понимаю?

2022-03-22 13:50 UTC, alesia-pashuk commented on tasks/cycles/cycles.js
> +for (let key of substr) {
Согласна. Переименовала и let убрала, раз у нас там цикл for. 
<img width="260" alt="3" src="https://user-images.githubusercontent.com/91085705/159496772-ebaf1714-a038-45b3-bc2c-568bd7d155c3.PNG">

2022-03-22 14:11 UTC, alesia-pashuk commented on tasks/cycles/cycles.js
> +i = 1;
Здесь не догоняю. Смотри, если я закомментирую i, то у меня уже неверно считает, т.к. n = 10, а по условию увеличиваем значение мы до тех пор, пока i < n. Я должна ожидать, что у меня значение i будет подхвачено из цикла for, но происходят какие-то чушь и путаница... Это их ты имел в виду выше?
 
<img width="266" alt="4" src="https://user-images.githubusercontent.com/91085705/159500623-ec871858-c527-4543-8407-7714f34ed32d.png">

2022-03-22 19:02 UTC, merged