3d_lesson_corrections
alesia-pashuk/js-mentoring-program pull request #4
Opened 2022-03-22 19:22 UTC by alesia-pashuk

Женя, прости, что измен весь файл целиком. Как я и боялась, граната в моих руках мартышки взорвалась. Хорошо, что скопировала себе отдельно документы, а то пришлось бы по новой делать 3-й урок. 

Предыдущий бранч смерджила, вопросы к нему порезолвила. Не уверена, что надо было делать именно так, но уже сделала. Не смогла вспомнить, чтобы мы обсуждали, как надо было сделать. Поправь меня и тут, если надо.

2022-03-27 13:33 UTC, eugs requested changes

2022-03-27 13:33 UTC, eugs commented on tasks/cycles/cycles.js
> + i = 1;
то же самое со счётчиком, использовать старые нежелательно (когда они созданы на одном уровне со всеми циклами)
лучше создать новый счётчик для нового цикла

2022-03-27 13:33 UTC, eugs commented on tasks/cycles/cycles.js
> + i = 1;
всё же лучше создать новую переменную для нового цикла, напр, `let j = 1;`

2022-03-27 13:33 UTC, eugs commented on tasks/cycles/cycles.js
> +     personIncomes.salary +
получается, что мы во всём цикле перебираем разные `value`, но нигде их не используем
тут в `totalIncome` каждый раз записывается одно и то же выражение с захардкоженными переменными, а смысл цикла как раз в том, чтоб перебрать все имеющиеся (без хардкода)

если в `personIncomes` добавятся новые поля, то они не запишутся в `totalIncome`

2022-03-28 16:01 UTC, alesia-pashuk commented on tasks/cycles/cycles.js
> +     personIncomes.salary +
<img width="635" alt="1" src="https://user-images.githubusercontent.com/91085705/160439511-560cc21d-7006-4b55-a7db-692eac0979a6.PNG">

наконец дошло

2022-03-28 16:02 UTC, closed without merging